name: wishlink
description: "Social and Interactive Wish List Platform - The Future of Gift-Giving"
publish_to: 'none'

version: 1.0.0+25

environment:
  sdk: ^3.8.1

dependencies:
  font_awesome_flutter: ^10.10.0
  flutter:
    sdk: flutter
  
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  cloud_functions: ^6.0.5
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7
  flutter_local_notifications: ^19.5.0

  intl: ^0.20.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  http: ^1.6.0
  html: ^0.15.6


  shared_preferences: ^2.5.4

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Geist-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon.png"

flutter_native_splash:
  android: true
  ios: true

  color: "#ffffff"
  image: assets/images/LogoBlack.png

  color_dark: "#000000"
  image_dark: assets/images/Logo.png



