name: wishlink
description: "Social and Interactive Wish List Platform - The Future of Gift-Giving"
publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: ^3.8.1

dependencies:
  font_awesome_flutter: ^10.10.0
  flutter:
    sdk: flutter
  
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  flutter_local_notifications: ^17.2.1

  intl: ^0.20.2
  url_launcher_android: ^6.3.17
  url_launcher_ios: ^6.3.4
  url_launcher: ^6.2.5
  share_plus: ^10.0.0
  http: ^1.2.2
  html: ^0.15.4


  shared_preferences: ^2.2.2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  firebase_storage: ^13.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon.png"


